name: Test NPM Authentication

on:
  workflow_dispatch:

jobs:
  test-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Test NPM Token
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Testing NPM authentication..."
          
          # Create .npmrc with token
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          
          # Test whoami
          echo "Running npm whoami:"
          npm whoami || echo "FAILED: whoami command"
          
          # Test access to pr-vibe
          echo -e "\nChecking access to pr-vibe:"
          npm access ls-packages | grep pr-vibe || echo "No access to pr-vibe found"
          
          # Check token format (without exposing it)
          if [ -z "$NODE_AUTH_TOKEN" ]; then
            echo "ERROR: NPM_TOKEN secret is empty!"
          else
            echo "NPM_TOKEN is set (length: ${#NODE_AUTH_TOKEN} characters)"
            echo "Token starts with: ${NODE_AUTH_TOKEN:0:8}..."
          fi
          
          # Clean up
          rm ~/.npmrc